### Default ###
spring:
  profiles:
    active: local
jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES

---

### Local Environment ###
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update



google:
  fcm:
    api_url: ENC(k7NAWqUEDKT1lBPaXLaE4rSWP9nR4g4OXU2lpMp9iLAmEU/SPc9U3Ypd/t7+byWuUcpTNQyGSJY1cY3oI57urz+ZLsPICHoEi3Rh+m9WmP8=)
    json: ENC(n9AOWbLwj4Bnum2xZHLjz7mC+Y6ueM0seB2dt1XYRPVf4z4v5zreKob2MlG00X08c6y1c5Yh9tOYo6EwYMtj4w==)

---

### Deployment Environment ###
server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: ENC(c4Nz2EhgAW1fi5ATdDbAoU1AAq33Wr57)
spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(hlZ9mtKhfgV/ohMUAgImHRqMTjbLMqur/1o59wCEa8EQO5OMhGn6iR5WbUCGu2Dmn3IwSxTUjnD0FzoEZ/yVnO886MemFv1u3s0T2pIdaf5OI9EUttLfI/hl4JISmmM51i4UXKfnNgtSt4d42PMBGaoCVdgOt/i26Sx1oRYeeRpJ7yC7gUw38pywDEcrP5Av)
    username: ENC(KsA89EdM9qElTzUjbkalmA==)
    password: ENC(I3JTMr1UlL3AtX7NCOi3ufp0ZhCGv5A1)

google:
  fcm:
    api_url: ENC(k7NAWqUEDKT1lBPaXLaE4rSWP9nR4g4OXU2lpMp9iLAmEU/SPc9U3Ypd/t7+byWuUcpTNQyGSJY1cY3oI57urz+ZLsPICHoEi3Rh+m9WmP8=)
    json: ENC(n9AOWbLwj4Bnum2xZHLjz7mC+Y6ueM0seB2dt1XYRPVf4z4v5zreKob2MlG00X08c6y1c5Yh9tOYo6EwYMtj4w==)

