server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: ENC(c4Nz2EhgAW1fi5ATdDbAoU1AAq33Wr57)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(NZ/DDjnt+e7x9CncI/mYxuT4+KY7sX11Vhk/657v7xp/4S3fFwxQDnmMv2FkggxH4HQOGPNlZYFlVHN997jaWJYA2jjoU5sF+ws1gig6e2z6oAX2Zg/8x6GK+F2yjV+GTL8VfHQe5qCFOSqbxMrYENUDB9g/QmL/mRh+cnesSfrMCo9gGKwytDqlWUJndKv3)
    username: ENC(KsA89EdM9qElTzUjbkalmA==)
    password: ENC(B9TOcc4OMoQkuI7b4WyGlGlFDVTUU8D7)
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  h2:
    console:
      enabled: true
google:
  fcm:
    api_url: ENC(k7NAWqUEDKT1lBPaXLaE4rSWP9nR4g4OXU2lpMp9iLAmEU/SPc9U3Ypd/t7+byWuUcpTNQyGSJY1cY3oI57urz+ZLsPICHoEi3Rh+m9WmP8=)
    json: ENC(n9AOWbLwj4Bnum2xZHLjz7mC+Y6ueM0seB2dt1XYRPVf4z4v5zreKob2MlG00X08c6y1c5Yh9tOYo6EwYMtj4w==)

jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES