server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: ENC(c4Nz2EhgAW1fi5ATdDbAoU1AAq33Wr57)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(+fQUdxbmIMzrbLaT/OxOEfBccYWDP3MjDk0lH6OeP9Jzwb6Yr9JkTxUJN/E4SOZHGUBwcniEeoDe3cyboGjwzp2pWuadUoZwKZ1aLAAHhlqHukpa/MrGYxHYQObuZTeQGcYb67EiKs5ZLz9BadGgMF03ZDzEgfDOthdAMLBVQ+xcf+h4ZFK6ENtivtZ/4tKj)
    username: ENC(KsA89EdM9qElTzUjbkalmA==)
    password: ENC(I3JTMr1UlL3AtX7NCOi3ufp0ZhCGv5A1)
#spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  h2:
    console:
      enabled: true
      path: /h2-console
google:
  fcm:
    api_url: ENC(k7NAWqUEDKT1lBPaXLaE4rSWP9nR4g4OXU2lpMp9iLAmEU/SPc9U3Ypd/t7+byWuUcpTNQyGSJY1cY3oI57urz+ZLsPICHoEi3Rh+m9WmP8=)
    json: ENC(n9AOWbLwj4Bnum2xZHLjz7mC+Y6ueM0seB2dt1XYRPVf4z4v5zreKob2MlG00X08c6y1c5Yh9tOYo6EwYMtj4w==)

jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
    algorithm: PBEWithMD5AndDES